---
- name: Update system and reboot if necessary
  hosts: all
  become: yes
  tasks:
    - name: Determine OS distribution
      set_fact:
        os_family: "{{ ansible_os_family }}"

    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: os_family == "Debian"

    - name: Update RedHat/Fedora systems
      yum:
        name: '*'
        state: latest
      when: os_family == "RedHat"

    - name: Check if reboot is required
      register: reboot_required
      command: needs-restarting
      changed_when: false
      when: os_family == "RedHat"

    - name: Check if reboot is required (Debian/Ubuntu)
      register: reboot_required_ubuntu
      command: /usr/bin/systemctl is-system-running
      changed_when: false
      when: os_family == "Debian"

    - name: Reboot the system
      reboot:
      when: (reboot_required.rc == 1) or (reboot_required_ubuntu.stdout != 'running')

