---
- name: Update system and reboot if necessary
  hosts: all
  become: yes
  tasks:
    - name: Determine OS distribution
      set_fact:
        os_family: "{{ ansible_os_family }}"

    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: os_family == "Debian"

    - name: Update RedHat/Fedora systems
      yum:
        name: '*'
        state: latest
      when: os_family == "RedHat"

    - name: Check if a reboot is required for Debian/Ubuntu
      command: /usr/bin/dpkg --get-selections | grep -c '^linux-image'
      register: kernel_count
      changed_when: false
      when: os_family == "Debian"

    - name: Check if a reboot is required for RedHat/Fedora
      command: needs-restarting
      register: reboot_required
      changed_when: false
      when: os_family == "RedHat"

    - name: Reboot the system if required for Debian/Ubuntu
      reboot:
      when: kernel_count.stdout|int > 0

    - name: Reboot the system if required for RedHat/Fedora
      reboot:
      when: reboot_required.rc == 1
